app/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path('login/',views.loginPage,name="login"),
    path('register/',views.registerUser,name="register"),
    path('logout/',views.logout_user,name="logout"),
    path('',views.home,name="home"),
    path('room/<str:pk>/',views.room,name="room"),
    path('profile/<str:pk>',views.userProfile,name='user-profile'),
    path('create-room/',views.createRoom,name="create-room"),
    path('update-room/<str:pk>/',views.updateRoom,name="update-room"),
    path('delete-room/<str:pk>/',views.deleteRoom,name="delete-room"),
    path('delete-message/<str:pk>/',views.deleteMessage,name="delete-message"),
    path('update-user/',views.updateUser,name="update-user"),
    path('topics/',views.topicsPage,name='topics'),
    path('activity/',views.activitiesPage,name='activity'),
]

project/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls')),
    path('api/',include('app.api.urls')),
]
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    name = models.CharField(max_length=200,null=True)
    email = models.EmailField(null=True,unique=True)
    bio = models.TextField(null=True)
    
    avatar = models.ImageField(null=True,default = "avatar.svg")
    
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS=[]

  
class Topic(models.Model):
    name = models.CharField(max_length=200)
    def __str__(self):
        return self.name
     
class Room(models.Model):
    host = models.ForeignKey(User,on_delete=models.SET_NULL,null=True)
    topic = models.ForeignKey(Topic,on_delete=models.SET_NULL,null=True)
    name = models.CharField(max_length=200)
    description = models.TextField(null=True,blank=True)
    participants = models.ManyToManyField(User,related_name='participants',blank = True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.name
    class Meta:
        ordering = ['-updated','-created']
        
class Message(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    room = models.ForeignKey(Room,on_delete=models.CASCADE)
    body = models.TextField()
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.body[0:50]
    
    class Meta:
        ordering = ['updated','created']

app/templates/app/activity.html
{% extends 'main.html' %}
{% block content %}
    <main class="layout">
      <div class="container">
        <div class="layout__box">
          <div class="layout__boxHeader">
            <div class="layout__boxTitle">
              <a href="{{request.META.HTTP_REFERER}}">
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>arrow-left</title>
                  <path
                    d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z"
                  ></path>
                </svg>
              </a>
              <h3>Recent Activities</h3>
            </div>
          </div>

          <div class="activities-page layout__body">
          {% for message in room_messages %}
    <div class="activities__box">
        <div class="activities__boxHeader roomListRoom__header">
            <a href="{% url 'user-profile' message.user.id %}" class="roomListRoom__author">
                <div class="avatar avatar--small">
                    <img src="{{message.user.avatar.url}}" />
                </div>
                <p>
                    @{{message.user}}
                    <span>{{message.created|timesince}}</span>
                </p>
            </a>

            {% if request.user == message.user %}
            <div class="roomListRoom__actions">
                <a href="{% url 'delete-message' message.id %}">
                    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                        <title>remove</title>
                        <path
                            d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z">
                        </path>
                    </svg>
                </a>
            </div>
            {% endif %}
        </div> <!-- Close the roomListRoom__header div HERE -->

        <div class="activities__boxContent">
            <p>replied to post "<a href="{% url 'room' message.room.id %}">{{message.room.name}}</a>"</p>
            <div class="activities__boxRoomContent">
                {{message.body}}
            </div>
        </div>
    </div>
    {% endfor %}
          </div>
        </div>
      </div>
    </main>
{% endblock content %}

app/templates/app/activity_component.html
<div class="activities">
    <div class="activities__header">
        <h2>Recent Activities</h2>
    </div>
    
    {% for message in room_messages %}
    <div class="activities__box">
        <div class="activities__boxHeader roomListRoom__header">
            <a href="{% url 'user-profile' message.user.id %}" class="roomListRoom__author">
                <div class="avatar avatar--small">
                    <img src="{{message.user.avatar.url}}" />
                </div>
                <p>
                    @{{message.user}}
                    <span>{{message.created|timesince}}</span>
                </p>
            </a>

            {% if request.user == message.user %}
            <div class="roomListRoom__actions">
                <a href="{% url 'delete-message' message.id %}">
                    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                        <title>remove</title>
                        <path
                            d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z">
                        </path>
                    </svg>
                </a>
            </div>
            {% endif %}
        </div> <!-- Close the roomListRoom__header div HERE -->

        <div class="activities__boxContent">
            <p>replied to post "<a href="{% url 'room' message.room.id %}">{{message.room.name}}</a>"</p>
            <div class="activities__boxRoomContent">
                {{message.body}}
            </div>
        </div>
    </div>
    {% endfor %}
</div>

app/templates/app/delete_form.html
{% extends 'main.html' %}

{% block content %}
    <main class="delete-item layout">
        <div class="container">
            <div class="layout__box">
                <div class="layout__boxHeader">
                    <div class="layout__boxTitle">
                        <a href="{{request.META.HTTP_REFERER}}">
                            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                                viewBox="0 0 32 32">
                                <title>arrow-left</title>
                                <path
                                    d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
                                </path>
                            </svg>
                        </a>
                        <h3>Back</h3>
                    </div>
                </div>
                <div class="layout__body">
                    <form class="form" method ="POST" action ="">
                        {% csrf_token %}
                        <div class="form__group">
                            <p>Are you sure you want to delete "{{obj}}"</p>
                        </div>

                        <div class="for__group">
                            <input class="btn btn--main" type="submit" value="Confirm" />
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </main>
{% endblock content %}

app/templates/app/home.html
{% extends  'main.html' %}
{% block content%}
    <main class="layout layout--3">
      <div class="container">
        <!-- Topics Start -->
        {% include 'app/topics_component.html' %}
        <!-- Topics End -->

        <!-- Room List Start -->
        <div class="roomList">
          <div class="mobile-menu">
            <form class="{% url 'home' %}" method="GET" class="header__search">
              <label>
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>search</title>
                  <path
                    d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z"
                  ></path>
                </svg>
                <input placeholder="Search for posts" />
              </label>
            </form>
            <div class="mobile-menuItems">
              <a class="btn btn--main btn--pill" href="{% url 'topics' %}">Browse Topics</a>
              <a class="btn btn--main btn--pill" href="#">Recent Activities</a>
            </div>
          </div>

 
          <div class="roomList__header">
            <div>
              <h2>Study Room</h2>
              <p>{{room_count}}&nbsp;Rooms available</p>
            </div>
            <a class="btn btn--main" href="{%url 'create-room' %}">
              <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>add</title>
                <path
                  d="M16.943 0.943h-1.885v14.115h-14.115v1.885h14.115v14.115h1.885v-14.115h14.115v-1.885h-14.115v-14.115z"
                ></path>
              </svg>
              Create Room
            </a>
          </div>
        {% include 'app/room_component.html' %}
        </div>
        <!-- Room List End -->

        <!-- Activities Start -->
         {% include 'app/activity_component.html' %}
        <!-- Activities End -->
      </div>
    </main>
 {% endblock content %}

app/templates/app/login_register.html
{% extends 'main.html' %}
{% block content%}
    <main class="auth layout">
      {% if page == 'login' %}
        <div class="container">
        <div class="layout__box">
          <div class="layout__boxHeader">
            <div class="layout__boxTitle">
              <h3>Login</h3>
            </div>
          </div>
          <div class="layout__body">
            <h2 class="auth__tagline">Find your study partner</h2>

            <form class="form" method="POST" action="">
              {% csrf_token %}
              <div class="form__group form__group">
                <label for="room_name">Email</label>
                <input id="username" name="email" type="text" placeholder="eg.username_name" />
              </div>
              <div class="form__group">
                <label for="password">Password</label>
                <input
                  id="password"
                  name="password"
                  type="password"
                  placeholder="&bull;&bull;&bull;&bull;&bull;&bull;&bull;&bull;"
                />
              </div>

              <button class="btn btn--main" type="submit">
                <svg
                  version="1.1"
                  xmlns="http://www.w3.org/2000/svg"
                  width="32"
                  height="32"
                  viewBox="0 0 32 32"
                >
                  <title>lock</title>
                  <path
                    d="M27 12h-1v-2c0-5.514-4.486-10-10-10s-10 4.486-10 10v2h-1c-0.553 0-1 0.447-1 1v18c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-18c0-0.553-0.447-1-1-1zM8 10c0-4.411 3.589-8 8-8s8 3.589 8 8v2h-16v-2zM26 30h-20v-16h20v16z"
                  ></path>
                  <path
                    d="M15 21.694v4.306h2v-4.306c0.587-0.348 1-0.961 1-1.694 0-1.105-0.895-2-2-2s-2 0.895-2 2c0 0.732 0.413 1.345 1 1.694z"
                  ></path>
                </svg>

                Login
              </button>
            </form>

            <div class="auth__action">
              <p>Haven't signed up yet?</p>
              <a href="{% url 'register' %}" class="btn btn--link">Sign Up</a>
            </div>
          </div>
        </div>
      </div>
      {% else %}
      <div class="container">
        <div class="layout__box">
          <div class="layout__boxHeader">
            <div class="layout__boxTitle">
              <h3>Login</h3>
            </div>
          </div>
          <div class="layout__body">
            <h2 class="auth__tagline">Find your study partner</h2>

            <form class="form" method="POST" action="">
              {% csrf_token %}
              {% for field in form %}
              <div class="form__group form__group">
                <label for="room_name">{{field.label}}</label>
                {{field}}
              </div>
              {% endfor %}
              <button class="btn btn--main" type="submit">
                <svg
                  version="1.1"
                  xmlns="http://www.w3.org/2000/svg"
                  width="32"
                  height="32"
                  viewBox="0 0 32 32"
                >
                  <title>lock</title>
                  <path
                    d="M27 12h-1v-2c0-5.514-4.486-10-10-10s-10 4.486-10 10v2h-1c-0.553 0-1 0.447-1 1v18c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-18c0-0.553-0.447-1-1-1zM8 10c0-4.411 3.589-8 8-8s8 3.589 8 8v2h-16v-2zM26 30h-20v-16h20v16z"
                  ></path>
                  <path
                    d="M15 21.694v4.306h2v-4.306c0.587-0.348 1-0.961 1-1.694 0-1.105-0.895-2-2-2s-2 0.895-2 2c0 0.732 0.413 1.345 1 1.694z"
                  ></path>
                </svg>

                Register
              </button>
            </form>

            <div class="auth__action">
              <p>Already Signed up?</p>
              <a href="{% url 'login' %}" class="btn btn--link">Login</a>
            </div>
          </div>
        </div>
      </div>
      {% endif %}
    </main>
{% endblock content %}

app/templates/app/profile.html
{% extends  'main.html' %}


{% block content%}
  <main class="profile-page layout layout--3">
    <div class="container">
      <!-- Topics Start -->
      {% include 'app/topics_component.html' %}
      <!-- Topics End -->

      <!-- Room List Start -->
      <div class="roomList">
        <div class="profile">
          <div class="profile__avatar">
            <div class="avatar avatar--large active">
              <img src="{{user.avatar.url}}" />
            </div>
          </div>
          <div class="profile__info">
            <h3>{{user.username}}</h3>
            <p>@{{user.username}}</p>

            {% if request.user == user%}
            <a href="{% url 'update-user' %}" class="btn btn--main btn--pill">Edit Profile</a>
            {% endif %}
          </div>
          <div class="profile__about">
            <h3>About</h3>
          </div>
        </div>

        <div class="roomList__header">
          <div>
            <h2>Study Rooms Hosted by {{user.username}}</a>
            </h2>
          </div>
        </div>
       {% include 'app/room_component.html' %}   
      </div>
      <!-- Room List End -->

      <!-- Activities Start -->
       {% include 'app/activity_component.html' %} 
      <!-- Activities End -->
    </div>
  </main>
{% endblock %}

app/templates/app/room.html
{% extends 'main.html' %}

{% block content %}
<main class="profile-page layout layout--2">
    <div class="container">
        <!-- Room Start -->
        <div class="room">
            <div class="room__top">
                <div class="room__topLeft">
                    <a href="{% url 'home' %}">
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                            <title>arrow-left</title>
                            <path d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z"></path>
                        </svg>
                    </a>
                    <h3>Study Room</h3>
                </div>

                {% if room.host == request.user %}
                <div class="room__topRight">
                    <a href="{% url 'update-room' room.id %}">
                        <svg enable-background="new 0 0 24 24" height="32" viewBox="0 0 24 24" width="32" xmlns="http://www.w3.org/2000/svg">
                            <title>edit</title>
                            <g>
                                <path d="m23.5 22h-15c-.276 0-.5-.224-.5-.5s.224-.5.5-.5h15c.276 0 .5.224.5.5s-.224.5-.5.5z" />
                            </g>
                            <g>
                                <g>
                                    <path d="m2.5 22c-.131 0-.259-.052-.354-.146-.123-.123-.173-.3-.133-.468l1.09-4.625c.021-.09.067-.173.133-.239l14.143-14.143c.565-.566 1.554-.566 2.121 0l2.121 2.121c.283.283.439.66.439 1.061s-.156.778-.439 1.061l-14.142 14.141c-.065.066-.148.112-.239.133l-4.625 1.09c-.038.01-.077.014-.115.014zm1.544-4.873-.872 3.7 3.7-.872 14.042-14.041c.095-.095.146-.22.146-.354 0-.133-.052-.259-.146-.354l-2.121-2.121c-.19-.189-.518-.189-.707 0zm3.081 3.283h.01z"/>
                                </g>
                                <g>
                                    <path d="m17.889 10.146c-.128 0-.256-.049-.354-.146l-3.535-3.536c-.195-.195-.195-.512 0-.707s.512-.195.707 0l3.536 3.536c.195.195.195.512 0 .707-.098.098-.226.146-.354.146z"/>
                                </g>
                            </g>
                        </svg>
                    </a>
                    <a href="{% url 'delete-room' room.id %}">
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                            <title>remove</title>
                            <path d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"></path>
                        </svg>
                    </a>
                </div>
                {% endif %}
            </div>

            <div class="room__box scroll">
                <div class="room__header scroll">
                    <div class="room__info">
                        <h3>{{room.name}}</h3>
                        <span>{{room.created | timesince}} ago</span>
                    </div>
                    <div class="room__hosted">
                        <p>Hosted By</p>
                        <a href="{% url 'user-profile' room.host.id %}" class="room__author">
                            <div class="avatar avatar--small">
                                <img src="{{room.host.avatar.url}}" />
                            </div>
                            <span>
                                {% if room.host.name %}
                                    {{ room.host.name }}
                                {% else %}
                                    {{ room.host.username }}
                                {% endif %}
                            </span>
                        </a>
                    </div>
                    <span class="room__topics">{{room.topic}}</span>
                </div>

                <div class="room__conversation">
                    <div class="threads scroll">
                        {% for message in room_messages %}
                        <div class="thread">
                            <div class="thread__top">
                                <div class="thread__author">
                                    <a href="{% url 'user-profile' message.user.id %}" class="thread__authorInfo">
                                        <div class="avatar avatar--small">
                                            <img src="{{message.user.avatar.url}}" /> <!-- FIXED: was room.host.avatar.url -->
                                        </div>
                                        <span>
                                            {% if message.user.name %}
                                                {{ message.user.name }}
                                            {% else %}
                                                {{ message.user.username }}
                                            {% endif %}
                                        </span>
                                    </a>
                                    <span class="thread__date">{{message.created | timesince}} ago</span>
                                </div>
                                
                                {% if request.user == message.user %}
                                <a href="{% url 'delete-message' message.id %}">
                                    <div class="thread__delete">
                                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                                            <title>remove</title>
                                            <path d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"></path>
                                        </svg>
                                    </div>
                                </a>
                                {% endif %}
                            </div>
                            <div class="thread__details">
                                {{message.body}}
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>

            <!-- Message Form - Only show if user is authenticated -->
            {% if request.user.is_authenticated %}
            <div class="room__message">
                <form action="" method="POST">
                    {% csrf_token %}
                    <input name="body" placeholder="Write your message here..." required />
                    <button type="submit" class="btn btn--main">Send Message</button>
                </form>
            </div>
            {% else %}
            <div class="room__message">
                <div class="alert alert--info">
                    <p>Please <a href="{% url 'login' %}">login</a> to send messages in this room.</p>
                </div>
            </div>
            {% endif %}
        </div>
        <!-- Room End -->

        <!-- Participants Start -->
        <div class="participants">
            <h3 class="participants__top">Participants <span>({{ participants.count }})</span></h3>
            <div class="participants__list scroll">
                {% for user in participants %}
                <a href="{% url 'user-profile' user.id %}" class="participant">
                    <div class="avatar avatar--medium">
                        <img src="{{ user.avatar.url }}" /> <!-- FIXED: was message.user.avatar.url -->
                    </div>
                    <p>
                        {% if user.name %}
                            {{ user.name }}
                        {% else %}
                            {{ user.username }}
                        {% endif %}
                        <span>@{{ user.username }}</span>
                    </p>
                </a>
                {% endfor %}
            </div>
        </div>
        <!-- Participants End -->
    </div>
</main>
{% endblock content %}

app/templates/app/room_component.html
{% for room in rooms %}
<div class="roomListRoom">
            <div class="roomListRoom__header">
              {% if room.host %}
              <a href="{% url 'user-profile' room.host.id %}" class="roomListRoom__author">
                 <div class="avatar avatar--small">
                      <img src="{{room.host.avatar.url}}" />
                </div>
                <span>@{{room.host.username}}</span>
             </a>
            {% else %}
            <div class="roomListRoom__author">
                <div class="avatar avatar--small">
                    <img src="https://randomuser.me/api/portraits/men/37.jpg" />
                </div>
                <span>No Host</span>
            </div>
            {% endif %}
              <div class="roomListRoom__actions">
                <span>{{room.created | timesince}}</span>
              </div>
            </div>
            <div class="roomListRoom__content">
              <a href="{% url 'room' room.id %}">{{room.name}}</a>
            </div>
            <div class="roomListRoom__meta">
              <a href="{% url 'room' room.id%}" class="roomListRoom__joined">
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>user-group</title>
                  <path
                    d="M30.539 20.766c-2.69-1.547-5.75-2.427-8.92-2.662 0.649 0.291 1.303 0.575 1.918 0.928 0.715 0.412 1.288 1.005 1.71 1.694 1.507 0.419 2.956 1.003 4.298 1.774 0.281 0.162 0.456 0.487 0.456 0.85v4.65h-4v2h5c0.553 0 1-0.447 1-1v-5.65c0-1.077-0.56-2.067-1.461-2.584z"
                  ></path>
                  <path
                    d="M22.539 20.766c-6.295-3.619-14.783-3.619-21.078 0-0.901 0.519-1.461 1.508-1.461 2.584v5.65c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-5.651c0-1.075-0.56-2.064-1.461-2.583zM22 28h-20v-4.65c0-0.362 0.175-0.688 0.457-0.85 5.691-3.271 13.394-3.271 19.086 0 0.282 0.162 0.457 0.487 0.457 0.849v4.651z"
                  ></path>
                  <path
                    d="M19.502 4.047c0.166-0.017 0.33-0.047 0.498-0.047 2.757 0 5 2.243 5 5s-2.243 5-5 5c-0.168 0-0.332-0.030-0.498-0.047-0.424 0.641-0.944 1.204-1.513 1.716 0.651 0.201 1.323 0.331 2.011 0.331 3.859 0 7-3.141 7-7s-3.141-7-7-7c-0.688 0-1.36 0.131-2.011 0.331 0.57 0.512 1.089 1.075 1.513 1.716z"
                  ></path>
                  <path
                    d="M12 16c3.859 0 7-3.141 7-7s-3.141-7-7-7c-3.859 0-7 3.141-7 7s3.141 7 7 7zM12 4c2.757 0 5 2.243 5 5s-2.243 5-5 5-5-2.243-5-5c0-2.757 2.243-5 5-5z"
                  ></path>
                </svg>
                {{room.participants.all.count}} Joined
              </a>
              <p class="roomListRoom__topic">{{room.topic.name}}</p>
            </div>
</div>
{% endfor %}

app/templates/app/topics.html
{% extends 'main.html' %}
{% block content %}
    <main class="create-room layout">
      <div class="container">
        <div class="layout__box">
          <div class="layout__boxHeader">
            <div class="layout__boxTitle">
              <a href="{% url 'home' %}">
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>arrow-left</title>
                  <path
                    d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z"
                  ></path>
                </svg>
              </a>
              <h3>Browse Topics</h3>
            </div>
          </div>

          <div class="topics-page layout__body">
            <form action="" method="GET" class="header__search">
              <label>
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>search</title>
                  <path
                    d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z"
                  ></path>
                </svg>
                <input name="q" placeholder="Search for topics" />
              </label>
            </form>

            <ul class="topics__list">
              <li>
                <a href="{% url 'topics' %}" class="active">All <span>{{topics.count}}</span></a>
              </li>
              {% for topic in topics%}
              <li>
                <a href="{% url 'home' %}?q={{topic.name}}">{{ topic.name }} <span>{{topic.room_set.all.count}}</span></a>
              </li>
             {% endfor %}
            </ul>
          </div>
        </div>
      </div>
    </main>
{% endblock content %}

app/templates/app/topics_component.html
 <div class="topics">
          <div class="topics__header">
            <h2>Browse Topics</h2>
          </div>
          <ul class="topics__list">
            <li>
              <a href="{% url 'home' %}" class="active">All <span>{{topics.count}}</span></a>
            </li>
            {% for topic in topics%}
            <li>
              <div> 
                <a href = "{% url 'home' %}?q={{topic.name}}">{{topic.name}}<span>{{topic.room_set.all.count}}</span></a>
              </div>
            </li>
            {% endfor %}
          </ul>
          <a class="btn btn--link" href="{% url 'topics' %}">
            More
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>chevron-down</title>
              <path d="M16 21l-13-13h-3l16 16 16-16h-3l-13 13z"></path>
            </svg>
          </a>
        </div>
    